// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDljsy6wP0BaJznxN3m9L4fbCcT3kdgnrM',
    appId: '1:683002421235:web:53c7a0ae69a19a9f357c86',
    messagingSenderId: '683002421235',
    projectId: 'chatapp-88e11',
    authDomain: 'chatapp-88e11.firebaseapp.com',
    storageBucket: 'chatapp-88e11.appspot.com',
    measurementId: 'G-KJNK4JH83G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsaTReVzHMhaDwdMqISjJB6_q0O_KiK9s',
    appId: '1:683002421235:android:d8a4f7380dfebd4e357c86',
    messagingSenderId: '683002421235',
    projectId: 'chatapp-88e11',
    storageBucket: 'chatapp-88e11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIBKTqWYlA-3A7WYShByznodKOSVZ4dg',
    appId: '1:683002421235:ios:6e3279342712837e357c86',
    messagingSenderId: '683002421235',
    projectId: 'chatapp-88e11',
    storageBucket: 'chatapp-88e11.appspot.com',
    iosBundleId: 'com.hvd2737.chatAppsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFIBKTqWYlA-3A7WYShByznodKOSVZ4dg',
    appId: '1:683002421235:ios:6e3279342712837e357c86',
    messagingSenderId: '683002421235',
    projectId: 'chatapp-88e11',
    storageBucket: 'chatapp-88e11.appspot.com',
    iosBundleId: 'com.hvd2737.chatAppsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDljsy6wP0BaJznxN3m9L4fbCcT3kdgnrM',
    appId: '1:683002421235:web:ee7d7e68bc5ed85a357c86',
    messagingSenderId: '683002421235',
    projectId: 'chatapp-88e11',
    authDomain: 'chatapp-88e11.firebaseapp.com',
    storageBucket: 'chatapp-88e11.appspot.com',
    measurementId: 'G-DL2VVHG1FC',
  );
}
